services:
  # PHP/Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-portal-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - web-portal-network
    depends_on:
      - db
      - redis

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: web-portal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-portal-network
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: web-portal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: web_portal
      MYSQL_USER: web_portal_user
      MYSQL_PASSWORD: web_portal_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - web-portal-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: web-portal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - web-portal-network

  # Node.js for building assets
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: web-portal-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - web-portal-network
    command: npm run dev

volumes:
  db_data:
    driver: local

networks:
  web-portal-network:
    driver: bridge

